/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          "on-secondary-fixed": "#002113",
          "primary-fixed-dim": "#c0c1ff",
          "on-tertiary-container": "#f9fdff",
          "primary-fixed": "#e1e0ff",
          "on-surface-variant": "#464554",
          "secondary-fixed": "#6ffbbe",
          "inverse-on-surface": "#eff1f3",
          "inverse-surface": "#2d3133",
          "on-primary-container": "#fffbff",
          "surface-container-low": "#f2f4f6",
          "background": "#f7f9fb",
          "tertiary-fixed": "#acedff",
          "on-primary-fixed": "#07006c",
          "on-secondary": "#ffffff",
          "on-primary": "#ffffff",
          "secondary-container": "#6cf8bb",
          "on-surface": "#191c1e",
          "inverse-primary": "#c0c1ff",
          "on-primary-fixed-variant": "#2f2ebe",
          "on-tertiary": "#ffffff",
          "surface-tint": "#494bd6",
          "on-secondary-fixed-variant": "#005236",
          "surface": "#f7f9fb",
          "surface-container-highest": "#e0e3e5",
          "outline-variant": "#c7c4d7",
          "error": "#ba1a1a",
          "on-tertiary-fixed": "#001f26",
          "on-secondary-container": "#00714d",
          "tertiary-container": "#008096",
          "secondary": "#006c49",
          "surface-container-high": "#e6e8ea",
          "surface-dim": "#d8dadc",
          "on-error-container": "#93000a",
          "error-container": "#ffdad6",
          "on-error": "#ffffff",
          "on-tertiary-fixed-variant": "#004e5c",
          "surface-container": "#eceef0",
          "on-background": "#191c1e",
          "surface-variant": "#e0e3e5",
          "tertiary-fixed-dim": "#4cd7f6",
          "surface-bright": "#f7f9fb",
          "tertiary": "#006577",
          "secondary-fixed-dim": "#4edea3",
          "primary": "#4648d4",
          "outline": "#767586",
          "surface-container-lowest": "#ffffff",
          "primary-container": "#6063ee"
        },
        borderRadius: {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
        },
        spacing: {
          "stack-xl": "48px",
          "unit": "4px",
          "gutter": "24px",
          "stack-sm": "8px",
          "stack-xs": "4px",
          "container-max": "1280px",
          "stack-md": "16px",
          "margin-desktop": "40px",
          "stack-lg": "24px",
          "margin-mobile": "16px"
        },
        fontFamily: {
          "headline-lg": ["Geist", "sans-serif"],
          "label-md": ["Geist", "sans-serif"],
          "body-sm": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "display-lg": ["Geist", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "headline-md": ["Geist", "sans-serif"],
          "headline-lg-mobile": ["Geist", "sans-serif"],
          "label-sm": ["Geist", "sans-serif"]
        },
        fontSize: {
          "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
          "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
          "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
          "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
          "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
          "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
          "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
          "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
          "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }]
        }
      },
    },
    plugins: [
      require('@tailwindcss/forms'),
      require('@tailwindcss/container-queries'),
    ],
  }